[info]
game-name = "Wind Waker: Debug Menu"
full-game-name = "Wind Waker: Debug Menu"
developer-name = "Speedrun Community"
full-developer-name = "Wind Waker Speedrun Community"
description = "Allows for more control over the game"
image = "banner.png"

[src]
iso = "gzlj01.iso"
src = "code"
link = ["code/target/powerpc-unknown-linux-gnu/release/librust.a"]
patch = "code/src/patch.asm"

[build]
map = "target/framework.map"
iso = "target/rom_hack.iso"

[link]
entries = ["init", "game_loop", "read_controller"]
base = "0x8040_1000"
